### PR TITLE
GraphQL language support

### PR DESCRIPTION
**Pull request by langpavel**
Add GraphQL coloring and delegates block strings (mostly [used for descriptions](https://facebook.github.io/graphql/draft/#sec-Descriptions)) to markdown

### CODE REVIEW

**Comment by langpavel** [comment]
Hi @alexandrudima can you help me? If you can look and give me some clue, or if you can ask community for help..

I'm also curious if full language service for GraphQL can be easily implemented instead of this PR :thinking: 

I really wish Monaco editor as default in Graph*i*QL soon :slightly_smiling_face:

**Comment by alexandrudima** [comment]
@langpavel I think starting small and slowly improving is definitely the right way to go about this! I am happy to help with specific technical questions, but I am sorry I don't have the necessary time to learn the GraphQL syntax and then help with the syntax highlighter per se.

But I can help with examples or specific questions.

Also, if you get only basic coloring working, I am happy to merge that in. We can always refine it later on, IMHO it doesn't need to be perfect to ship. I also don't really have a magic wand to gather contributors for this colorizer. The best is for your to bring it in some shippable state, then I can merge it, and then hopefully people start using it and then will want to come and improve it with other PRs.

**Comment by langpavel** [comment]
Hi @alexandrudima 

I think that basic coloring working is there and it can be shipped. As you said, we can always refine it later :-)

**Comment by langpavel** [comment]
I will add nested MarkDown support for block strings today

**Comment by langpavel** [comment]
Now I'm super excited :champagne: 
graphql-preview

**Comment by alexandrudima** [comment]
Unfortunately not, the background cannot be controlled from the tokens+themes at this time.

**Comment by alexandrudima** [comment]
Thank you!

**Pull request merged**
