### PR TITLE
Add Scala support

### PR DESCRIPTION
**Pull request by ALANVF**
Added support for Scala syntax highlighting. Added some cool stuff like context-sensitive highlighting and some support for Dotty (Scala 3) syntax.

Here's an screenshot of some example code using the mode:
image

### CODE REVIEW

**Comment by alexdima** [comment]
Thank you!

**Comment by ALANVF** [comment]
Hey btw the usage of `keyword.flow` was completely intentional because there isn't any other way to use the color it provides.

**Comment by alexdima** [comment]
Tokenization should be semantical, so we should not use `keyword.flow` i.e. generate a keyword token instead of an identifier token due to the default theme or because one color looks better.

It is possible to customize the theme and change the color of any token.

**Comment by ALANVF** [comment]
That makes sense I guess. I just hadn't thought about it because the monarch playground editor doesn't let you change the token colors

**Pull request merged**
