### PR TITLE
Overhaul of ABAP language based on release 7.54

### PR DESCRIPTION
**Pull request by mbtools**
Long overdue update to the ABAP language definition based on the most recent release.

References:
https://help.sap.com/doc/abapdocu_754_index_htm/7.54/en-US/index.htm (general)
https://help.sap.com/doc/abapdocu_754_index_htm/7.54/en-US/index.htm?file=abenabap_words.htm (keywords)
https://help.sap.com/doc/abapdocu_754_index_htm/7.54/en-US/index.htm?file=abenoperators.htm (operators)
https://help.sap.com/doc/abapdocu_754_index_htm/7.54/en-US/index.htm?file=abenbuilt_in_types.htm (types)

### CODE REVIEW

**Comment by mbtools** [comment]
sorry, I can't tell what's wrong. please have a look at the build log

**Comment by larshp** [comment]
looks like the unit test is failing,
https://dev.azure.com/ms/monaco-languages/_build/results?buildId=110976&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=bd05475d-acb5-5619-3ccb-c46842dbc997

image

**Comment by alexdima** [comment]
@mbtools Please run the test locally by running `npm run test` and push a commit to fix the test if the change was intentional.

**Review by alexdima — CHANGES_REQUESTED** [review]
Please fix failing tests.

**Comment by alexdima** [comment]
Thank you!

**Pull request merged**
