### PR TITLE
[ST] Some updated for Structured Text Language support

### PR DESCRIPTION
**Pull request by Serhioromano**
- Autoformat code beautifications added spaces before `}`
- Reorder some rules for better priority
- Update some Regex for a better match
- Added new rule to highlight variables after `.`

### CODE REVIEW

**Comment by alexandrudima** [comment]
Thank you!

**Comment by Serhioromano** [comment]
When you see monaco demo, and switch to the language, the demo code is loaded to the editor. Where do I save this? There is that piece of code? I've created `example.iecst` file in the root, how to make this load to the demo editor?

**Comment by alexandrudima** [comment]
@Serhioromano the samples live here -- https://github.com/microsoft/monaco-editor/tree/master/website/index/samples ... It would be great to have a PR with the `.iecst` file.

**Comment by Serhioromano** [comment]
Added but all extensions are TXT could not make file `.iecst`

**Comment by alexandrudima** [comment]
That's fine.

**Pull request merged**
