### PR TITLE
Support better C++ annotation highlighting

### PR DESCRIPTION
**Pull request by mattgodbolt**
* Uses some simple highlighting within annotations
* Supports multi-line annotations
  (see compiler-explorer/compiler-explorer#878)

### CODE REVIEW

**Comment by mattgodbolt** [comment]
Hold up: I just realised `[ [ this ] ]` is valid too. Will at least port the fix from https://github.com/starkmapper/compiler-explorer/commit/f2cdfbb393e9da6ddce07552cce8cb7fa8c686ab

**Comment by mattgodbolt** [comment]
Done, ready. Thanks for your patience, and attention!

**Comment by mattgodbolt** [comment]
Hey friends, µping on this :) Would let us close off a bug in Compiler Explorer _and_ mean we don't monkeypatch our version of monaco :)

**Comment by alexdima** [comment]
:+1: Thank you!

**Comment by mattgodbolt** [comment]
Fantastic! Thanks @alexdima :)

**Pull request merged**
