### PR TITLE
Support literal interpolated strings ($@"")

### PR DESCRIPTION
**Pull request by jmarianer**

### CODE REVIEW

**Comment by alexandrudima** [comment]
Thank you! :heart:

**Comment by jmarianer** [comment]
Sorry for the multiple closes and opens; I was told to do this as part of confirming that I am a Microsoft employee. They also said it could take some time to propagate, so I'll try doing it again over the weekend or on Monday.

**Comment by sandyarmstrong** [comment]
This looks nice! Anything holding up a merge at this point?

**Comment by alexandrudima** [comment]
Thank you @jmarianer :heart: !

**Pull request merged**
