### PR TITLE
Pascal language support

### PR DESCRIPTION
**Pull request by alefragnani**
Adds basic Pascal language support, with syntax highlighting, auto-closing pairs and code folding.

### CODE REVIEW

**Comment by ALANVF** [comment]
You kinda messed up on the escape sequences; Pascal doesn't have any. Add a `#\d+` rule for control strings (the pascal equivalent of escape sequences, but they aren't in strings). If you're still confused, maybe look at [this](https://stackoverflow.com/questions/2975048/what-is-the-symbol-in-pascal)

**Comment by alefragnani** [comment]
Hi @ALANVF ,

You are right. I ended up forgetting to remove/update that `escapes` rule 👍 . The only real escape would be `'`, when close to another `'`. 

About the `\#d+` rule for control string, I’m not so sure if it should be added, because `#27` Can represent an hex number or the `chr(27)` string, depending on where it is being used.

I’ll update the PR with your comments, thank you 👍

**Comment by ALANVF** [comment]
No problem, I'm suprosed I caught it. As for the control string, maybe you can make a rule to highlight it if it is placed next to a string, or just highlight it anyways since it means something special either way.

**Comment by alexandrudima** [comment]
:+1: Thank you

**Pull request merged**
